name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish to AWS Elastic Beanstalk
        uses: einaregilsson/aws-elastic-beanstalk-deploy@v3
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ASPAssignment
          environment_name: ASPAssignment-env
          version_label: ${{ github.sha }}
          wait: true