name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output publish

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v16.1.0
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'ASPAssignment'
          environment_name: 'ASPAssignment-env'
          region: 'us-east-1'
          version_label: 'v${{ github.sha }}'
          deployment_package: 'publish'