name: Deploy to Elastic Beanstalk


on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'


      - name: Build and publish
        run: dotnet publish -c Release -o ./publish
       
      - name: Zip content
        run: ls -la && zip hello.zip ./publish

      - name: Upload to S3
        run: aws s3 cp hello.zip s3://deploymentasp

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli


      - name: Create Application Version
        run: aws elasticbeanstalk create-application-version --application-name ASPAssignment --version-label $GITHUB_SHA --source-bundle S3Bucket="deploymentasp",S3Key="hello.zip"

      - name: Update Application Version 
        run: aws elasticbeanstalk update-environment  --application-name ASPAssignment --environment-name ASPAssignment-env --version-label $GITHUB_SHA 
       
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          ASPNETCORE_ENVIRONMENT: "Production"
          ASPNETCORE_URLS: "http://+:80"
          AWS_EC2_METADATA_DISABLED: true


