name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo pip3 install awsebcli

      - name: Initialize Elastic Beanstalk environment
        run: eb init ASPAssignment-env --region us-east-1 --platform "64bit Amazon Linux 2 v2.5.3 running .NET 6.0"

      - name: Deploy to AWS Elastic Beanstalk
        run: eb deploy