name: Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install zip
    - name: Build and package
      run: |
        dotnet publish --configuration Release --output ./publish
        cd publish
        zip -r ../myapp.zip *
        cd ..
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v15
      with:
        aws-region: us-east-1
        application-name: ASPAssignment
        environment-name: ASPAssignment-env
        version-label: ${{ github.sha }}
        deployment-package: ./ASPAssignment.zip