name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Build project
      run: dotnet build --configuration Release
      
    - name: Publish project
      run: dotnet publish -c Release -o ./publish
      
    - name: Zip files
      run: zip -r publish.zip publish
      
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v19
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: "ASPAssignment"
        environment_name: "ASPAssignment-env"
        version_label: ${{ github.sha }}
        region: "us-east-1"
        deployment_package: "publish.zip"
        command: "dotnet publish/WebApplication100.dll"